"""Sanity tests for core.native_app_installer — paths, manifest structure,
and the forbidden-systemd-deps guard.

These run without a device. They protect against accidental refactors that
would write a unit file containing dependencies that caused a factory reset
on 3.22 (see comments in resources/xochitl-nowatchdog.conf).
"""
import os

import pytest  # noqa: F401  # used by @pytest.mark.parametrize below

from core import native_app_installer as nai


def test_per_service_paths_are_consistent():
    """All per-service paths must live under /home/root/xovi/services/xochitl.service/."""
    assert nai.DEST_DIR.startswith("/home/root/xovi/services/xochitl.service/")
    assert nai.XOVI_PER_SERVICE_EXT_DIR.startswith(
        "/home/root/xovi/services/xochitl.service/"
    )


def test_appload_release_url_uses_latest():
    """We want /latest/download/ so we never pin to a broken version (v0.5.1
    panicked on firmware 3.27 hashes)."""
    assert "releases/latest/download" in nai.APPLOAD_GITHUB_URL
    assert nai.APPLOAD_GITHUB_URL.endswith(".zip")


def test_app_files_manifest_present():
    """APP_FILES must always include the manifest and compiled QML bundle."""
    root_files = nai.APP_FILES.get("", [])
    assert "manifest.json" in root_files
    assert "resources.rcc" in root_files


def test_app_files_backend_entry_present():
    """The backend launcher script must be in APP_FILES so it gets uploaded."""
    backend = nai.APP_FILES.get("backend", [])
    assert "entry" in backend
    assert "main.py" in backend


def test_native_app_root_resolves():
    """Running from source, native_app_root() returns the nativeapp/ subdir."""
    root = nai.native_app_root()
    assert os.path.isdir(root)
    assert os.path.basename(root) == "nativeapp"


def test_resources_dir_resolves():
    """_resources_dir() should point at the repo's resources/ folder."""
    res = nai._resources_dir()
    assert os.path.isdir(res)
    assert os.path.basename(res) == "resources"


def test_all_app_files_exist_on_disk():
    """Every file listed in APP_FILES must actually exist in nativeapp/
    (except resources.rcc which is build-generated). Missing files would cause
    an opaque install-time error."""
    root = nai.native_app_root()
    missing = []
    for subdir, names in nai.APP_FILES.items():
        for name in names:
            if name == "resources.rcc":
                continue  # generated by nativeapp/build.sh
            path = os.path.join(root, subdir, name) if subdir else os.path.join(root, name)
            if not os.path.isfile(path):
                missing.append(path)
    assert not missing, f"Missing nativeapp files: {missing}"


@pytest.mark.parametrize("forbidden", ["Requires=", "Wants=", "After=", "Before=", "BindsTo="])
def test_resource_unit_files_have_no_dangerous_deps(forbidden):
    """Drop-in unit files written to persistent rootfs must NEVER contain
    cross-unit dependencies. A misplaced `Requires=` caused a factory reset
    on firmware 3.22. The installer enforces this at runtime; this test makes
    sure the resource files we ship don't trip the guard."""
    resources = nai._resources_dir()
    for fname in ("xochitl-nowatchdog.conf", "rm-emergency-override.conf"):
        path = os.path.join(resources, fname)
        if not os.path.isfile(path):
            continue
        with open(path) as f:
            content = f.read()
        assert forbidden not in content, (
            f"{fname} contains forbidden '{forbidden}' — would trip install-time guard"
        )
